name: rabbitmq-testing
services:
  rabbitmq:
    image: rabbitmq:3.13-management
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    deploy:
      mode: replicated
      replicas: 1

  webapi:
    build:
      context: ReceiverWebApi
      dockerfile: Dockerfile
    restart: always
    ports:
      - "5050:8080"
      - "5051:8081"
    environment:
      ASPNETCORE_ENVIRONMENT: Production
  